participation_edit:
    path:      /participation_edit/{id}
    defaults:  { _controller: WelcomangoParticipationBundle:AdminParticipation:edit }
    requirements:
        id: \d+

participation_delete:
    path:      /participation_delete/{id}
    defaults:  { _controller: WelcomangoParticipationBundle:AdminParticipation:delete }
    requirements:
        id: \d+