imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi:             ~
    translator:      { fallbacks: "%locale%" }
    translator: ~
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form:
        resources: ['bootstrap_3_layout.html.twig']

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        default_entity_manager: default
        auto_generate_proxy_classes: "%kernel.debug%"
        entity_managers:
            default:
                naming_strategy: doctrine.orm.naming_strategy.underscore
                auto_mapping: true
                mappings:
                    model:
                        type: annotation
                        dir: %kernel.root_dir%/../src/Welcomango/Model
                        prefix: Welcomango\Model
                        alias: Model
                        is_bundle: false

swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

fos_user:
    db_driver: orm
    firewall_name: main
    user_class: Welcomango\Model\User
    registration:
        confirmation:
            enabled: true

knp_menu:
    twig:
        template: WelcomangoCoreBundle:Menu:knp_menu.html.twig

knp_paginator:
    page_range: 5                      # default page range used in pagination control
    default_options:
        page_name: page                # page query parameter name
        sort_field_name: sort          # sort field query parameter name
        sort_direction_name: direction # sort direction query parameter name
        distinct: true                 # ensure distinct results, useful when ORM queries are using GROUP BY statements
    template:
        pagination: WelcomangoCoreBundle:AdminCRUD:pagination_twitter_bootstrap_3_sliding.html.twig # sliding pagination controls template
        sortable: KnpPaginatorBundle:Pagination:sortable_link.html.twig # sort link template

genemu_form:
    select2: ~
    image:
        enabled:  true
        selected: 'large'
        filters:  ['crop']
        thumbnails:
            small:  [100, 100]
            medium: [200, 200]
            large:  [500, 500]

stof_doctrine_extensions:
    # default_locale: fr
    # this causes the translations to be BLANK when they dont exist.
    # Don't know if this is the desired behavior or not
    # translation_fallback: true
    orm:
        default:
            timestampable: true
            # this is now manually activated in Ylly\YllyTranslationBundle\DependencyInjection\YllyTranslationExtBundleExtension
            # translatable: true
            loggable: true
            sortable: true

gregwar_image: ~

services:
    twig.extension.text:
        class: Twig_Extensions_Extension_Text
        tags:
            - { name: twig.extension }
    twig.extension.date:
        class: Twig_Extensions_Extension_Date
        tags:
            - { name: 'twig.extension' }

fos_message:
    db_driver: orm
    thread_class: Welcomango\Model\Thread
    message_class: Welcomango\Model\Message
    composer: welcomango.message.composer
    sender: welcomango.message.sender

oneup_uploader:
    mappings:
        gallery:
            namer: welcomango.media_namer
            frontend: dropzone
            storage:
                type: gaufrette
                filesystem: gaufrette.gallery_filesystem

knp_gaufrette:
    adapters:
        gallery:
            local:
                directory: %kernel.root_dir%/../web/medias/tmp
                create: true
        real:
            local:
                directory: %kernel.root_dir%/../web/medias
                create: true
        experiences:
            local:
                directory: %kernel.root_dir%/../web/medias/experiences
                create: true
    filesystems:
        real:
            adapter: real
        gallery:
            adapter: gallery
        experience:
            adapter: experiences

liip_imagine:
    resolvers:
       default:
          web_path: ~

    filter_sets:
        cache: ~
        thumb120:
            quality: 100
            filters:
                thumbnail: { size: [120, 120], mode: outbound }
        thumb250:
            quality: 100
            filters:
                thumbnail: { size: [250, 250], mode: outbound }

welcomango_booking:
    available_status:
        - Available
        - Happened
        - Booked
        - Requested
        - Accepted
        - Refused
        - Cancelled
    meeting_times:
        - Early Morning
        - Morning
        - Lunchtime
        - Afternoon
        - Evening
        - Night
