welcomango_user_bundle:
    resource: "@WelcomangoUserBundle/Controller/"
    type:     annotation
    prefix:   /

welcomango_media_bundle:
    resource: "@WelcomangoMediaBundle/Controller/"
    type:     annotation
    prefix:   /


welcomango_core_bundle:
    resource: "@WelcomangoCoreBundle/Controller/"
    type:     annotation
    prefix:   /

welcomango_experience_bundle:
    resource: "@WelcomangoExperienceBundle/Controller/"
    type:     annotation
    prefix:   /

welcomango_participation_bundle:
    resource: "@WelcomangoParticipationBundle/Controller/"
    type:     annotation
    prefix:   /

welcomango_fos_routing:
    resource: "@WelcomangoUserBundle/Resources/config/routing.yml"
