welcomango_admin_participation:
    resource: "@WelcomangoAdminParticipationBundle/Controller/"
    type:     annotation
    prefix:   /

welcomango_common_base:
    resource: "@WelcomangoCommonBaseBundle/Controller/"
    type:     annotation
    prefix:   /

welcomango_front_experience_bundle:
    resource: "@WelcomangoFrontExperienceBundle/Controller/"
    type:     annotation
    prefix:   /

welcomango_front_core_bundle:
    resource: "@WelcomangoFrontCoreBundle/Controller/"
    type:     annotation
    prefix:   /

welcomango_front_crm_bundle:
    resource: "@WelcomangoFrontCrmBundle/Controller/"
    type:     annotation
    prefix:   /

welcomango_admin_core_bundle:
    resource: "@WelcomangoAdminCoreBundle/Controller/"
    type:     annotation
    prefix:   /

welcomango_admin_crm_bundle:
    resource: "@WelcomangoAdminCrmBundle/Controller/"
    type:     annotation
    prefix:   /

welcomango_admin_experience_bundle:
    resource: "@WelcomangoAdminExperienceBundle/Controller/"
    type:     annotation
    prefix:   /

admin_user_bundle:
   resource: "@WelcomangoAdminCrmBundle/Resources/config/routing.yml"

front_user_bundle:
   resource: "@WelcomangoFrontCrmBundle/Resources/config/routing.yml"
