welcomango_front_experience:
    resource: "@WelcomangoFrontExperienceBundle/Controller/"
    type:     annotation
    prefix:   /

welcomango_front_core:
    resource: "@WelcomangoFrontCoreBundle/Controller/"
    type:     annotation
    prefix:   /

welcomango_front_bundle_crm:
    resource: "@WelcomangoFrontCrmBundle/Controller/"
    type:     annotation
    prefix:   /

welcomango_admin_crm:
    resource: "@WelcomangoCrmBundle/Controller/"
    type:     annotation
    prefix:   /

welcomango_admin_experience:
    resource: "@WelcomangoExperienceBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

user_bundle:
   resource: "@WelcomangoCrmBundle/Resources/config/routing.yml"
