welcomango_front_bundle_crm:
    resource: "@WelcomangoFrontCrmBundle/Controller/"
    type:     annotation
    prefix:   /front/

welcomango_admin_crm:
    resource: "@WelcomangoAdminCrmBundle/Controller/"
    type:     annotation
    prefix:   /

welcomango_experience:
    resource: "@WelcomangoAdminExperienceBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

user_bundle:
   resource: "@WelcomangoAdminCrmBundle/Resources/config/routing.yml"
