welcomango_experience:
    resource: "@WelcomangoExperienceBundle/Controller/"
    type:     annotation
    prefix:   /

welcomango_crm:
    resource: "@WelcomangoCrmBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

user_bundle:
   resource: "@WelcomangoCrmBundle/Resources/config/routing.yml"