welcomango_user_bundle:
    resource: "@WelcomangoUserBundle/Controller/"
    type:     annotation
    prefix:   /

welcomango_media_bundle:
    resource: "@WelcomangoMediaBundle/Controller/"
    type:     annotation
    prefix:   /

welcomango_core_bundle:
    resource: "@WelcomangoCoreBundle/Controller/"
    type:     annotation
    prefix:   /

welcomango_experience_bundle:
    resource: "@WelcomangoExperienceBundle/Controller/"
    type:     annotation
    prefix:   /

welcomango_participation_bundle:
    resource: "@WelcomangoParticipationBundle/Controller/"
    type:     annotation
    prefix:   /

welcomango_fos_routing:
    resource: "@WelcomangoUserBundle/Resources/config/routing.yml"

genemu_upload:
    resource: "@GenemuFormBundle/Resources/config/routing/upload.xml"

genemu_image:
    resource: "@GenemuFormBundle/Resources/config/routing/image.xml"

fos_message:
    resource: "@FOSMessageBundle/Resources/config/routing.xml"
