welcomango_currency:
    resource: "@WelcomangoCurrencyBundle/Controller/"
    type:     annotation
    prefix:   /

welcomango_content:
    resource: "@WelcomangoContentBundle/Controller/"
    type:     annotation
    prefix:   /

welcomango_tag:
    resource: "@WelcomangoTagBundle/Controller/"
    type:     annotation
    prefix:   /

welcomango_booking:
    resource: "@WelcomangoBookingBundle/Controller/"
    type:     annotation
    prefix:   /

welcomango_user_bundle:
    resource: "@WelcomangoUserBundle/Controller/"
    type:     annotation
    prefix:   /

welcomango_media_bundle:
    resource: "@WelcomangoMediaBundle/Controller/"
    type:     annotation
    prefix:   /

welcomango_core_bundle:
    resource: "@WelcomangoCoreBundle/Controller/"
    type:     annotation
    prefix:   /

welcomango_experience_bundle:
    resource: "@WelcomangoExperienceBundle/Controller/"
    type:     annotation
    prefix:   /

welcomango_message_bundle:
    resource: "@WelcomangoMessageBundle/Controller/"
    type:     annotation

welcomango_fos_routing:
    resource: "@WelcomangoUserBundle/Resources/config/routing.yml"

genemu_upload:
    resource: "@GenemuFormBundle/Resources/config/routing/upload.xml"

genemu_image:
    resource: "@GenemuFormBundle/Resources/config/routing/image.xml"

fos_message:
    resource: "@FOSMessageBundle/Resources/config/routing.xml"

oneup_uploader:
    resource: .
    type: uploader

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"

# HWIOAuthBundle
hwi_oauth_security:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix: /connect

hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /connect

# We override this part of the routing
hwi_oauth_connect:
     resource: "@WelcomangoUserBundle/Resources/config/connect.xml"
     prefix: /connect

facebook_login:
    pattern: /connect/check-facebook

facebook_connect:
    pattern: /connect/facebook
