security:
   encoders:
       FOS\UserBundle\Model\UserInterface: sha512

   role_hierarchy:
       ROLE_SUPER_ADMIN: ROLE_SUPER_ADMIN
       ROLE_ADMIN: ROLE_ADMIN
       ROLE_USER: ROLE_USER

   providers:
       fos_userbundle:
           id: fos_user.user_provider.username_email

   firewalls:
       main:
           pattern: ^/
           form_login:
               check_path: /login_check
               login_path: /login
               provider: fos_userbundle
               default_target_path: /profile
               csrf_provider: form.csrf_provider
           oauth:
               resource_owners:
                   facebook:           "/connect/check-facebook"
               login_path:        /connect
               failure_path:      /connect

               oauth_user_provider:
                   service: hwi_oauth.user.provider.fosub_bridge
           logout:
               path:    /logout
               target: /
              # provider: fos_userbundle
              # csrf_provider: form.csrf_provider

           anonymous:    true
       login:
           pattern:  ^/login$
           security: false

           remember_me:
               key: "%secret%"
               lifetime: 31536000
               path: /
               domain: ~

   access_control:
       - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
       - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
       - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
       - { path: ^/welcomadmin/, role: ROLE_ADMIN }
       - { path: ^/welcomadmin, role: ROLE_ADMIN }

