participation_edit:
    path:      /participation_edit/{id}
    defaults:  { _controller: WelcomangoParticipationBundle:Participation:edit }
    requirements:
        id: \d+

participation_delete:
    path:      /participation_delete/{id}
    defaults:  { _controller: WelcomangoParticipationBundle:Participation:delete }
    requirements:
        id: \d+