experience_edit:
    path:      /experience_edit/{id}
    defaults:  { _controller: WelcomangoExperienceBundle:Experience:edit }
    requirements:
        id: \d+

experience_delete:
    path:      /experience_delete/{id}
    defaults:  { _controller: WelcomangoExperienceBundle:Experience:delete }
    requirements:
        id: \d+